export const dashboardRoute = [
    {
        slug:"",
        linkName:"Dashboard"
    },
    {
        slug:"",
        linkName:"Profile"
    },
    {
        slug:"/dashboard/table-data",
        linkName:"Create/Update/Delete"
    },
    {
        slug:"",
        linkName:"Apps"
    },
    {
        slug:"",
        linkName:"Settings"
    },
    {
        slug:"/dashboard/logout",
        linkName:"Logout"
    }
]